// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace schema
{

public enum Data : byte
{
 NONE = 0,
 CredentialToken = 1,
 ReconnectKey = 2,
 JoinRoomCommand = 3,
 PlayerInfo = 4,
 RoomInfo = 5,
};


}
