// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace schema
{

public enum Data : byte
{
 NONE = 0,
 JoinRoomCommand = 1,
 RoomInfo = 2,
 PlayerUpdate = 3,
 ErrorMessage = 4,
};


}
