// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace schema
{

public enum ErrorCode : sbyte
{
 Unknown = 0,
 INVALID_AUTH = 1,
 ROOM_NOT_FOUND = 2,
};


}
