// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace schema
{

public enum PlayerStatus : sbyte
{
 Unknown = 0,
 Arrive = 1,
 Left = 2,
};


}
