// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace schema
{

using global::System;
using global::FlatBuffers;

public struct ReconnectKey : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReconnectKey GetRootAsReconnectKey(ByteBuffer _bb) { return GetRootAsReconnectKey(_bb, new ReconnectKey()); }
  public static ReconnectKey GetRootAsReconnectKey(ByteBuffer _bb, ReconnectKey obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReconnectKey __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Key { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetKeyBytes() { return __p.__vector_as_arraysegment(4); }

  public static Offset<ReconnectKey> CreateReconnectKey(FlatBufferBuilder builder,
      StringOffset keyOffset = default(StringOffset)) {
    builder.StartObject(1);
    ReconnectKey.AddKey(builder, keyOffset);
    return ReconnectKey.EndReconnectKey(builder);
  }

  public static void StartReconnectKey(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddKey(FlatBufferBuilder builder, StringOffset keyOffset) { builder.AddOffset(0, keyOffset.Value, 0); }
  public static Offset<ReconnectKey> EndReconnectKey(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    builder.Required(o, 4);  // key
    return new Offset<ReconnectKey>(o);
  }
};


}
